server:
  port: 8050
spring:
  application:
    name: gateway
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: user #不暴露生产者