server:
  port: 8081
spring:
  application:
    name: user
  mvc:
    servlet:
      load-on-startup: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  config: classpath:log4j2.xml      