server:
  port: 8081
spring:
  application:
    name: user
  mvc:
    servlet:
      load-on-startup: 1
  user:
    oauth:
      clientId: api
      clientSecret: api
      checkTokenUrl: http://localhost:8050/auth/oauth/check_token #正式部署时localhost为网关IP地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      
logging:
  config: classpath:log4j2.xml      