server:
  port: 8083
spring:
  application:
    name: api
  mvc:
    servlet:
      load-on-startup: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true    
feign:
  hystrix:
    enabled: true
hystrix.command.default.execution.isolation.strategy: SEMAPHORE
logging:
  config: classpath:log4j2.xml      