server:
  port: 8761
spring:
  mvc:
    servlet:
      load-on-startup: 1  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  config: classpath:log4j2.xml      